files:
  - source: /advancementinfo/1.20-fabric0.83.0-1.4.json
    translation: /advancementinfo/1.20-fabric0.83.0-1.4/%locale_with_underscore%.json
    excluded_target_languages:
      - ja-JP
      - pt-BR
      - ru
      - tt-RU
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /amecsapi/1.5.1+mc1.20-pre1.json
    translation: /amecsapi/1.5.1+mc1.20-pre1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et-EE
      - it
      - ko-KR
      - pt-BR
      - pt
      - ru
      - tr
      - zh-HANS
  - source: /animatica/0.6+1.20.json
    translation: /animatica/0.6+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
  - source: /appleskin/2.5.1+mc1.20.json
    translation: /appleskin/2.5.1+mc1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - cs-CZ
      - de
      - fr
      - hy-AM
      - ko-KR
      - pl
      - ru
      - tr-TR
      - uk-UA
      - zh-CN
  - source: /betterf3/7.0.1.json
    translation: /betterf3/7.0.1/%locale_with_underscore%.json
    excluded_target_languages:
      - af-ZA
      - ar-SA
      - ast-ES
      - az
      - ba-RU
      - be-BY
      - bg
      - bn
      - br
      - bs
      - ca-ES
      - cs-CZ
      - cy-GB
      - da-DK
      - de-AT
      - de-CH
      - de
      - el-GR
      - en-AU
      - en-CA
      - en-GB
      - en-NZ
      - en-PT
      - en-UD
      - eo-UY
      - es-AR
      - es-CL
      - es-EC
      - es
      - es-MX
      - es-UY
      - es-VE
      - et-EE
      - eu-ES
      - fa-IR
      - fi
      - fil-PH
      - fo
      - fr-CA
      - fr
      - fra-DE
      - fy-NL
      - ga-IE
      - gd-GB
      - gl-ES
      - haw-US
      - he-IL
      - hi-IN
      - hu
      - hy-AM
      - id
      - ig-NG
      - io-EN
      - is
      - it
      - ja-JP
      - jbo-EN
      - ka-GE
      - kk-KZ
      - kn-IN
      - ko-KR
      - ku
      - la
      - lb-LU
      - li
      - lol-US
      - lt
      - lv
      - mk
      - mn
      - ms-MY
      - mt
      - nds-DE
      - nl-BE
      - nl
      - nn-NO
      - no
      - oc-FR
      - pl
      - pt-BR
      - pt
      - qya-AA
      - ro
      - ru
      - se-NO
      - sk
      - sl-SI
      - so
      - sq-AL
      - sr-SP
      - sv-SE
      - ta-IN
      - th
      - tl-PH
      - tlh-AA
      - tr
      - tt-RU
      - uk-UA
      - val-ES
      - vec-IT
      - vi-VN
      - yi-DE
      - yo-NG
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /blur/3.1.0.json
    translation: /blur/3.1.0/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - en-GB
      - fr
      - ko-KR
      - pt-BR
      - ru
      - sv-SE
      - uk-UA
      - zh-CN
  - source: /boatiview/0.0.5.json
    translation: /boatiview/0.0.5/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - pt-BR
      - zh-CN
  - source: /borderlessmining/1.1.8+1.20.1.json
    translation: /borderlessmining/1.1.8+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - it
      - ko-KR
      - pl
      - ru
      - tr
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /capes/1.5.2+1.20.json
    translation: /capes/1.5.2+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - cs-CZ
      - de
      - el-GR
      - et-EE
      - fr
      - id
      - it
      - pt-BR
      - pt
      - ru
      - tr
      - tt-RU
      - zh-CN
      - zh-TW
  - source: /chat_heads/0.10.22.json
    translation: /chat_heads/0.10.22/%locale_with_underscore%.json
    excluded_target_languages:
      - be-BY
      - de
      - fr
      - ja-JP
      - uk-UA
      - zh-CN
  - source: /citresewn/1.1.3+1.20.json
    translation: /citresewn/1.1.3+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et-EE
      - it
      - ko-KR
      - pt-BR
      - rs-SP
      - ru
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /citresewn-defaults/1.1.3+1.20.json
    translation: /citresewn-defaults/1.1.3+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - ru
      - zh-TW
  - source: /cloth-config2/11.1.106.json
    translation: /cloth-config2/11.1.106/%locale_with_underscore%.json
    excluded_target_languages:
      - bg
      - de
      - en-UD
      - et-EE
      - fr
      - ja-JP
      - lol-US
      - pt-BR
      - ru
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /coat/1.0.0-beta.20+mc1.20-pre1.json
    translation: /coat/1.0.0-beta.20+mc1.20-pre1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
  - source: /continuity/3.0.0-beta.4+1.20.1.json
    translation: /continuity/3.0.0-beta.4+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - cs-CZ
      - de
      - el-GR
      - et-EE
      - fil-PH
      - fr
      - it
      - ko-KR
      - pl
      - pt-BR
      - ru
      - uk-UA
      - zh-CN
  - source: /debugify/1.20.1+2.0.json
    translation: /debugify/1.20.1+2.0/%locale_with_underscore%.json
    excluded_target_languages:
      - el-GR
      - fr
      - pt-BR
      - ru
      - tr
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /durabilitytooltip/1.1.5.json
    translation: /durabilitytooltip/1.1.5/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - ru
      - zh-CN
  - source: /dynamic_fps/3.2.1.json
    translation: /dynamic_fps/3.2.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de-AT
      - de-CH
      - de
      - en-PT
      - es-AR
      - es-CL
      - es-EC
      - es
      - es-MX
      - es-UY
      - es-VE
      - et-EE
      - fr-CA
      - fr
      - it
      - ko-KR
      - pl
      - pt-BR
      - pt
      - ru
      - sv-SE
      - tr
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /entity_model_features/1.0.2.json
    translation: /entity_model_features/1.0.2/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - el-GR
      - fr
      - pt-BR
      - ru
      - vi-VN
      - zh-CN
      - zh-TW
  - source: /entity_texture_features/4.6.json
    translation: /entity_texture_features/4.6/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - ru
      - uk-UA
      - zh-CN
  - source: /entityculling/1.6.2-mc1.20.1.json
    translation: /entityculling/1.6.2-mc1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - it
      - pt-BR
      - ru
      - uk-UA
      - vi-VN
      - zh-TW
  - source: /fabricskyboxes/0.7.3+mc1.20.1.json
    translation: /fabricskyboxes/0.7.3+mc1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - vi-VN
      - zh-TW
  - source: /fabrishot/1.10.0.json
    translation: /fabrishot/1.10.0/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et-EE
      - fi
      - ru
      - zh-CN
      - zh-TW
  - source: /fallingleaves/1.15.4.json
    translation: /fallingleaves/1.15.4/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - ko-KR
      - pt-BR
      - ru
      - tr
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /fastquit/3.0.0+1.20+.json
    translation: /fastquit/3.0.0+1.20+/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et-EE
      - it
      - pl
      - ru
      - tr
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-TW
  - source: /fpsdisplay/3.1.0+1.20.x.json
    translation: /fpsdisplay/3.1.0+1.20.x/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es
      - pt-BR
      - zh-TW
  - source: /fsb-interop/1.3.6+mc1.20.1-build.50.json
    translation: /fsb-interop/1.3.6+mc1.20.1-build.50/%locale_with_underscore%.json
    excluded_target_languages:
      - zh-CN
      - zh-TW
  - source: /fullbrightnesstoggle/3.0.json
    translation: /fullbrightnesstoggle/3.0/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /held-item-info/1.5.0.json
    translation: /held-item-info/1.5.0/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - ru
      - zh-CN
  - source: /iris/1.6.10.json
    translation: /iris/1.6.10/%locale_with_underscore%.json
    excluded_target_languages:
      - cs-CZ
      - de-CH
      - de
      - en-PT
      - en-UD
      - es-AR
      - es
      - et-EE
      - fa-IR
      - fi
      - fr
      - hu
      - it
      - ja-JP
      - ko-KR
      - lol-US
      - nl
      - pl
      - pr-PT
      - pt-BR
      - ru
      - sk
      - th
      - tr
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /jade/11.6.2.json
    translation: /jade/11.6.2/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - it
      - ja-JP
      - ko-KR
      - pl
      - pt-BR
      - ru
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /lambdynlights/2.3.2+1.20.1.json
    translation: /lambdynlights/2.3.2+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es-MX
      - et-EE
      - fr-CA
      - fr
      - hi-IN
      - it
      - nl
      - pl
      - pt-BR
      - ru
      - sv-SE
      - tr
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-TW
  - source: /languagereload/1.5.9+1.20.1.json
    translation: /languagereload/1.5.9+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - be-BY
      - fr
      - it
      - ko-KR
      - pl
      - pt-BR
      - ru
      - tt-RU
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-TW
  - source: /libgui/8.0.2+1.20.json
    translation: /libgui/8.0.2+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - fi
      - fr
      - pt-BR
      - tt-RU
      - zh-CN
  - source: /libjf-config-core-v1/3.12.5.json
    translation: /libjf-config-core-v1/3.12.5/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /libjf-config-ui-tiny-v1/3.12.5.json
    translation: /libjf-config-ui-tiny-v1/3.12.5/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /libjf-web-v0/3.12.5.json
    translation: /libjf-web-v0/3.12.5/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /litematica/0.15.3.json
    translation: /litematica/0.15.3/%locale_with_underscore%.json
    excluded_target_languages:
      - ru
      - zh-CN
  - source: /malilib/0.16.2.json
    translation: /malilib/0.16.2/%locale_with_underscore%.json
    excluded_target_languages:
      - ru
      - tr
      - zh-CN
  - source: /midnightlib/1.4.1.json
    translation: /midnightlib/1.4.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - fr
      - pt-BR
      - tt-RU
      - uk-UA
      - zh-TW
  - source: /modmenu/7.2.2.json
    translation: /modmenu/7.2.2/%locale_with_underscore%.json
    excluded_target_languages:
      - af-ZA
      - an-ES
      - ar-SA
      - ast-ES
      - az
      - ba-RU
      - be-BY
      - bg
      - bn-BD
      - br-FR
      - bs-BA
      - ca-ES
      - ckb-IR
      - cs-CZ
      - csb-PL
      - cv-CU
      - cy-GB
      - da-DK
      - de-AT
      - de-CH
      - de
      - dsb-DE
      - el-GR
      - en-AU
      - en-CA
      - en-GB
      - en-NZ
      - en-PT
      - en-UD
      - eo-UY
      - es-AR
      - es-CL
      - es-EC
      - es
      - es-MX
      - es-UY
      - es-VE
      - et-EE
      - eu-ES
      - fa-IR
      - fi
      - fil-PH
      - fo
      - fr-CA
      - fr
      - fra-DE
      - fur-IT
      - fy-NL
      - ga-IE
      - gd-GB
      - gl-ES
      - got-DE
      - gv-IM
      - haw-US
      - he-IL
      - hi-IN
      - hr
      - hsb-DE
      - hu
      - hy-AM
      - id
      - ig-NG
      - io-EN
      - is
      - it
      - ja-JP
      - jbo-EN
      - ka-GE
      - kab-KAB
      - kk-KZ
      - kn-IN
      - ko-KR
      - kw-GB
      - la
      - lb-LU
      - li
      - lol-US
      - lt
      - lv
      - me-ME
      - mi-NZ
      - mk
      - mn
      - moh-CA
      - ms-MY
      - mt
      - nds-DE
      - ne-NP
      - nl-BE
      - nl
      - nn-NO
      - no
      - oc-FR
      - oj-CA
      - pl
      - pt-BR
      - pt
      - qya-AA
      - ro
      - ru
      - sah-SAH
      - se-NO
      - sk
      - sl-SI
      - so
      - sq-AL
      - sr-Cyrl-ME
      - sr-SP
      - sv-SE
      - ta-IN
      - th
      - tl-PH
      - tlh-AA
      - tr
      - tt-RU
      - tzl
      - uk-UA
      - ur-PK
      - uz-UZ
      - val-ES
      - vec-IT
      - vi-VN
      - yi-DE
      - yo-NG
      - zh-CN
      - zh-HK
      - zh-TW
      - zlm-Arab
  - source: /moreculling/1.20.1-0.19.0.json
    translation: /moreculling/1.20.1-0.19.0/%locale_with_underscore%.json
    excluded_target_languages:
      - et-EE
      - fr-CA
      - it
      - pt-BR
      - ru
      - tr
      - vi-VN
      - zh-CN
      - zh-TW
  - source: /mousewheelie/1.13.0+mc1.20.1.json
    translation: /mousewheelie/1.13.0+mc1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es-AR
      - et-EE
      - fi
      - fr
      - pl
      - pt-BR
      - zh-CN
  - source: /nochatreports/1.20.1-v2.2.2.json
    translation: /nochatreports/1.20.1-v2.2.2/%locale_with_underscore%.json
    excluded_target_languages:
      - ca-ES
      - cs-CZ
      - da-DK
      - de
      - en-PT
      - es
      - et-EE
      - fi
      - fr
      - id
      - it
      - ja-JP
      - ko-KR
      - nl
      - pl
      - pt-BR
      - ro
      - ru
      - sk
      - th
      - tr
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-TW
  - source: /notenoughanimations/1.6.4.json
    translation: /notenoughanimations/1.6.4/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - pt
      - uk-UA
      - zh-TW
  - source: /presencefootsteps/1.9.1.json
    translation: /presencefootsteps/1.9.1/%locale_with_underscore%.json
    excluded_target_languages:
      - cs-CZ
      - ja-JP
      - ko-KR
      - ru
      - tr
      - uk-UA
      - zh-CN
      - zh-TW
  - source: /puzzle/1.5.2+1.20.json
    translation: /puzzle/1.5.2+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - el-GR
      - et-EE
      - ko-KR
      - pl
      - pt-BR
      - ru
      - zh-CN
      - zh-TW
  - source: /reeses-sodium-options/1.6.5+mc1.20.1-build.95.json
    translation: /reeses-sodium-options/1.6.5+mc1.20.1-build.95/%locale_with_underscore%.json
    excluded_target_languages:
      - be-BY
      - pt-BR
      - ru
      - zh-CN
      - zh-TW
  - source: /roughlyenoughitems/12.0.674.json
    translation: /roughlyenoughitems/12.0.674/%locale_with_underscore%.json
    excluded_target_languages:
      - bg
      - cs-CZ
      - da-DK
      - de
      - en-GB
      - en-UD
      - eo-UY
      - es
      - et-EE
      - fr
      - he-IL
      - it
      - ja-JP
      - ko-KR
      - lol-US
      - nn-NO
      - pl
      - pt-BR
      - pt
      - ru
      - tr
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /roughlyenoughprofessions/2.0.2.json
    translation: /roughlyenoughprofessions/2.0.2/%locale_with_underscore%.json
    excluded_target_languages:
      - ja-JP
      - pt-BR
      - zh-CN
  - source: /roughlysearchable/2.6.0+1.20.1.json
    translation: /roughlysearchable/2.6.0+1.20.1/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /shulkerboxtooltip/4.0.4+1.20.1.json
    translation: /shulkerboxtooltip/4.0.4+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - en-GB
      - fr
      - ko-KR
      - pt-BR
      - ru
      - tr
      - uk-UA
      - zh-CN
  - source: /sodium/0.5.3.json
    translation: /sodium/0.5.3/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /sodium-extra/0.5.1+mc1.20.1-build.112.json
    translation: /sodium-extra/0.5.1+mc1.20.1-build.112/%locale_with_underscore%.json
    excluded_target_languages:
      - cs-CZ
      - de-AT
      - de-CH
      - de
      - el-GR
      - es-AR
      - es-MX
      - et-EE
      - fi
      - fr-CA
      - fr
      - it
      - ja-JP
      - ko-KR
      - ms-MY
      - pl
      - pt-BR
      - pt
      - ru
      - th
      - tr
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /sound_physics_remastered/1.20.1-1.2.1.json
    translation: /sound_physics_remastered/1.20.1-1.2.1/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - ru
  - source: /spruceui/5.0.0+1.20.json
    translation: /spruceui/5.0.0+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es
      - es-MX
      - et-EE
      - fr-CA
      - fr
      - it
      - pl
      - ru
      - zh-CN
      - zh-TW
  - source: /stack-to-nearby-chests/0.5.0.json
    translation: /stack-to-nearby-chests/0.5.0/%locale_with_underscore%.json
    excluded_target_languages:
      - zh-CN
  - source: /tweed4_tailor_screen/1.1.4+mc1.20-pre1.json
    translation: /tweed4_tailor_screen/1.1.4+mc1.20-pre1/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /visuality/0.7.1+1.20.json
    translation: /visuality/0.7.1+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - es-MX
      - pt-BR
      - ru
      - uk-UA
      - zh-CN
  - source: /wakes/0.2.0.json
    translation: /wakes/0.2.0/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /waterdripsound/1.19-0.3.2.json
    translation: /waterdripsound/1.19-0.3.2/%locale_with_underscore%.json
    excluded_target_languages: []
  - source: /waveycapes/1.3.2.json
    translation: /waveycapes/1.3.2/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - pt-BR
      - pt
      - zh-CN
  - source: /xaerominimap/23.8.4.json
    translation: /xaerominimap/23.8.4/%locale_with_underscore%.json
    excluded_target_languages:
      - cs-CZ
      - da-DK
      - de
      - el-GR
      - es-AR
      - es
      - es-MX
      - et-EE
      - fr
      - hr
      - hu
      - id
      - it
      - ja-JP
      - lv
      - nl
      - pl
      - pt-BR
      - pt
      - ru
      - sr-SP
      - th
      - tr
      - uk-UA
      - zh-CN
  - source: /xaeroworldmap/1.36.0.json
    translation: /xaeroworldmap/1.36.0/%locale_with_underscore%.json
    excluded_target_languages:
      - de
  - source: /zoomify/2.11.2.json
    translation: /zoomify/2.11.2/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - en-GB
      - es
      - es-MX
      - et-EE
      - fr
      - ja-JP
      - pt-BR
      - ru
      - tr
      - vi-VN
      - zh-CN
      - zh-TW
