files:
  - source: /advancementinfo/1.20-fabric0.83.0-1.4.json
    translation: /advancementinfo/1.20-fabric0.83.0-1.4/%locale_with_underscore%.json
    excluded_target_languages:
      - ja
      - pt-BR
      - ru
      - tt-RU
      - uk
      - zh-CN
      - zh-TW
  - source: /amecsapi/1.5.1+mc1.20-pre1.json
    translation: /amecsapi/1.5.1+mc1.20-pre1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et
      - it
      - ko
      - pt-BR
      - pt-PT
      - ru
      - tr
  - source: /animatica/0.6+1.20.json
    translation: /animatica/0.6+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
  - source: /appleskin/2.5.1+mc1.20.json
    translation: /appleskin/2.5.1+mc1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - cs
      - de
      - fr
      - hy-AM
      - ko
      - pl
      - ru
      - uk
      - zh-CN
  - source: /betterf3/7.0.1.json
    translation: /betterf3/7.0.1/%locale_with_underscore%.json
    excluded_target_languages:
      - af
      - ar
      - ast
      - az
      - ba
      - be
      - ca
      - cs
      - cy
      - da
      - de-AT
      - de-CH
      - de
      - el
      - en-AU
      - en-CA
      - en-GB
      - en-NZ
      - en-PT
      - en-UD
      - eo
      - es-AR
      - es-CL
      - es-EC
      - es-ES
      - es-MX
      - es-UY
      - es-VE
      - et
      - eu
      - fa
      - fi
      - fil
      - fo
      - fr-CA
      - fr
      - fra-DE
      - fy-NL
      - ga-IE
      - gd
      - gl
      - haw
      - he
      - hi
      - hu
      - hy-AM
      - id
      - ig
      - ido
      - is
      - it
      - ja
      - jbo
      - ka
      - kk
      - kn
      - ko
      - la-LA
      - lb
      - li
      - lol
      - lt
      - lv
      - mk
      - mn
      - ms
      - mt
      - nds
      - nl-BE
      - nl
      - nn-NO
      - 'no'
      - oc
      - pl
      - pt-BR
      - pt-PT
      - qya-AA
      - ro
      - ru
      - se
      - sk
      - sl
      - so
      - sq
      - sr
      - sv-SE
      - ta
      - th
      - tl
      - tlh-AA
      - tr
      - tt-RU
      - uk
      - val-ES
      - vec
      - vi
      - yi
      - yo
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /blur/3.1.0.json
    translation: /blur/3.1.0/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - en-GB
      - fr
      - ko
      - pt-BR
      - ru
      - sv-SE
      - uk
      - zh-CN
  - source: /boatiview/0.0.5.json
    translation: /boatiview/0.0.5/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - pt-BR
      - zh-CN
  - source: /borderlessmining/1.1.8+1.20.1.json
    translation: /borderlessmining/1.1.8+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - it
      - ko
      - pl
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /capes/1.5.2+1.20.json
    translation: /capes/1.5.2+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - cs
      - de
      - el
      - et
      - fr
      - id
      - it
      - pt-BR
      - pt-PT
      - ru
      - tr
      - tt-RU
      - zh-CN
      - zh-TW
  - source: /chat_heads/0.10.22.json
    translation: /chat_heads/0.10.22/%locale_with_underscore%.json
    excluded_target_languages:
      - be
      - de
      - fr
      - ja
      - uk
      - zh-CN
  - source: /citresewn/1.1.3+1.20.json
    translation: /citresewn/1.1.3+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et
      - it
      - ko
      - pt-BR
      - ru
      - uk
      - zh-CN
      - zh-TW
  - source: /citresewn-defaults/1.1.3+1.20.json
    translation: /citresewn-defaults/1.1.3+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - ru
      - zh-TW
  - source: /cloth-config2/11.1.106.json
    translation: /cloth-config2/11.1.106/%locale_with_underscore%.json
    excluded_target_languages:
      - bg
      - de
      - en-UD
      - et
      - fr
      - ja
      - lol
      - pt-BR
      - ru
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /coat/1.0.0-beta.20+mc1.20-pre1.json
    translation: /coat/1.0.0-beta.20+mc1.20-pre1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
  - source: /continuity/3.0.0-beta.4+1.20.1.json
    translation: /continuity/3.0.0-beta.4+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - cs
      - de
      - el
      - et
      - fil
      - fr
      - it
      - ko
      - pl
      - pt-BR
      - ru
      - uk
      - zh-CN
  - source: /debugify/1.20.1+2.0.json
    translation: /debugify/1.20.1+2.0/%locale_with_underscore%.json
    excluded_target_languages:
      - el
      - fr
      - pt-BR
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /durabilitytooltip/1.1.5.json
    translation: /durabilitytooltip/1.1.5/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - ru
      - zh-CN
  - source: /dynamic_fps/3.2.1.json
    translation: /dynamic_fps/3.2.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de-AT
      - de-CH
      - de
      - en-PT
      - es-AR
      - es-CL
      - es-EC
      - es-ES
      - es-MX
      - es-UY
      - es-VE
      - et
      - fr-CA
      - fr
      - it
      - ko
      - pl
      - pt-BR
      - pt-PT
      - ru
      - sv-SE
      - tr
      - uk
      - vi
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /entity_model_features/1.0.2.json
    translation: /entity_model_features/1.0.2/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - el
      - fr
      - pt-BR
      - ru
      - vi
      - zh-CN
      - zh-TW
  - source: /entity_texture_features/4.6.json
    translation: /entity_texture_features/4.6/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - ru
      - uk
      - zh-CN
  - source: /entityculling/1.6.2-mc1.20.1.json
    translation: /entityculling/1.6.2-mc1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - it
      - pt-BR
      - ru
      - uk
      - vi
      - zh-TW
  - source: /fabricskyboxes/0.7.3+mc1.20.1.json
    translation: /fabricskyboxes/0.7.3+mc1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - vi
      - zh-TW
  - source: /fabrishot/1.10.0.json
    translation: /fabrishot/1.10.0/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et
      - fi
      - ru
      - zh-CN
      - zh-TW
  - source: /fallingleaves/1.15.4.json
    translation: /fallingleaves/1.15.4/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - ko
      - pt-BR
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /fastquit/3.0.0+1.20+.json
    translation: /fastquit/3.0.0+1.20+/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - et
      - it
      - pl
      - ru
      - tr
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /fpsdisplay/3.1.0+1.20.x.json
    translation: /fpsdisplay/3.1.0+1.20.x/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es-ES
      - pt-BR
      - zh-TW
  - source: /fsb-interop/1.3.6+mc1.20.1-build.50.json
    translation: /fsb-interop/1.3.6+mc1.20.1-build.50/%locale_with_underscore%.json
    excluded_target_languages:
      - zh-CN
      - zh-TW
  - source: /fullbrightnesstoggle/3.0.json
    translation: /fullbrightnesstoggle/3.0/%locale_with_underscore%.json
  - source: /held-item-info/1.5.0.json
    translation: /held-item-info/1.5.0/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - ru
      - zh-CN
  - source: /iris/1.6.10.json
    translation: /iris/1.6.10/%locale_with_underscore%.json
    excluded_target_languages:
      - cs
      - de-CH
      - de
      - en-PT
      - en-UD
      - es-AR
      - es-ES
      - et
      - fa
      - fi
      - fr
      - hu
      - it
      - ja
      - ko
      - lol
      - nl
      - pl
      - pt-BR
      - ru
      - sk
      - th
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /jade/11.6.2.json
    translation: /jade/11.6.2/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - it
      - ja
      - ko
      - pl
      - pt-BR
      - ru
      - uk
      - zh-CN
      - zh-TW
  - source: /lambdynlights/2.3.2+1.20.1.json
    translation: /lambdynlights/2.3.2+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es-MX
      - et
      - fr-CA
      - fr
      - hi
      - it
      - nl
      - pl
      - pt-BR
      - ru
      - sv-SE
      - tr
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /languagereload/1.5.9+1.20.1.json
    translation: /languagereload/1.5.9+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - be
      - fr
      - it
      - ko
      - pl
      - pt-BR
      - ru
      - tt-RU
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /libgui/8.0.2+1.20.json
    translation: /libgui/8.0.2+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - fi
      - fr
      - pt-BR
      - tt-RU
      - zh-CN
  - source: /libjf-config-core-v1/3.12.5.json
    translation: /libjf-config-core-v1/3.12.5/%locale_with_underscore%.json
  - source: /libjf-config-ui-tiny-v1/3.12.5.json
    translation: /libjf-config-ui-tiny-v1/3.12.5/%locale_with_underscore%.json
  - source: /libjf-web-v0/3.12.5.json
    translation: /libjf-web-v0/3.12.5/%locale_with_underscore%.json
  - source: /litematica/0.15.3.json
    translation: /litematica/0.15.3/%locale_with_underscore%.json
    excluded_target_languages:
      - ru
      - zh-CN
  - source: /malilib/0.16.2.json
    translation: /malilib/0.16.2/%locale_with_underscore%.json
    excluded_target_languages:
      - ru
      - tr
      - zh-CN
  - source: /midnightlib/1.4.1.json
    translation: /midnightlib/1.4.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - fr
      - pt-BR
      - tt-RU
      - uk
      - zh-TW
  - source: /modmenu/7.2.2.json
    translation: /modmenu/7.2.2/%locale_with_underscore%.json
    excluded_target_languages:
      - af
      - ar
      - ast
      - az
      - ba
      - be
      - bg
      - br-FR
      - bs
      - ca
      - cs
      - cy
      - da
      - de-AT
      - de-CH
      - de
      - el
      - en-AU
      - en-CA
      - en-GB
      - en-NZ
      - en-PT
      - en-UD
      - eo
      - es-AR
      - es-CL
      - es-EC
      - es-ES
      - es-MX
      - es-UY
      - es-VE
      - et
      - eu
      - fa
      - fi
      - fil
      - fo
      - fr-CA
      - fr
      - fra-DE
      - fy-NL
      - ga-IE
      - gd
      - gl
      - haw
      - he
      - hi
      - hr
      - hu
      - hy-AM
      - id
      - ig
      - ido
      - is
      - it
      - ja
      - jbo
      - ka
      - kk
      - kn
      - ko
      - kw
      - la-LA
      - lb
      - li
      - lol
      - lt
      - lv
      - mi
      - mk
      - mn
      - ms
      - mt
      - nds
      - nl-BE
      - nl
      - nn-NO
      - 'no'
      - oc
      - pl
      - pt-BR
      - pt-PT
      - qya-AA
      - ro
      - ru
      - se
      - sk
      - sl
      - so
      - sq
      - sr
      - sv-SE
      - ta
      - th
      - tl
      - tlh-AA
      - tr
      - tt-RU
      - uk
      - val-ES
      - vec
      - vi
      - yi
      - yo
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /moreculling/1.20.1-0.19.0.json
    translation: /moreculling/1.20.1-0.19.0/%locale_with_underscore%.json
    excluded_target_languages:
      - et
      - fr-CA
      - it
      - pt-BR
      - ru
      - tr
      - vi
      - zh-CN
      - zh-TW
  - source: /mousewheelie/1.13.0+mc1.20.1.json
    translation: /mousewheelie/1.13.0+mc1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es-AR
      - et
      - fi
      - fr
      - pl
      - pt-BR
      - zh-CN
  - source: /nochatreports/1.20.1-v2.2.2.json
    translation: /nochatreports/1.20.1-v2.2.2/%locale_with_underscore%.json
    excluded_target_languages:
      - ca
      - cs
      - da
      - de
      - en-PT
      - es-ES
      - et
      - fi
      - fr
      - id
      - it
      - ja
      - ko
      - nl
      - pl
      - pt-BR
      - ro
      - ru
      - sk
      - th
      - tr
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /notenoughanimations/1.6.4.json
    translation: /notenoughanimations/1.6.4/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - pt-PT
      - uk
      - zh-TW
  - source: /presencefootsteps/1.9.1.json
    translation: /presencefootsteps/1.9.1/%locale_with_underscore%.json
    excluded_target_languages:
      - cs
      - ja
      - ko
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /puzzle/1.5.2+1.20.json
    translation: /puzzle/1.5.2+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - el
      - et
      - ko
      - pl
      - pt-BR
      - ru
      - zh-CN
      - zh-TW
  - source: /reeses-sodium-options/1.6.5+mc1.20.1-build.95.json
    translation: >-
      /reeses-sodium-options/1.6.5+mc1.20.1-build.95/%locale_with_underscore%.json
    excluded_target_languages:
      - be
      - pt-BR
      - ru
      - zh-CN
      - zh-TW
  - source: /roughlyenoughitems/12.0.674.json
    translation: /roughlyenoughitems/12.0.674/%locale_with_underscore%.json
    excluded_target_languages:
      - bg
      - cs
      - da
      - de
      - en-GB
      - en-UD
      - eo
      - es-ES
      - et
      - fr
      - he
      - it
      - ja
      - ko
      - lol
      - nn-NO
      - pl
      - pt-BR
      - pt-PT
      - ru
      - tr
      - uk
      - vi
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /roughlyenoughprofessions/2.0.2.json
    translation: /roughlyenoughprofessions/2.0.2/%locale_with_underscore%.json
    excluded_target_languages:
      - ja
      - pt-BR
      - zh-CN
  - source: /roughlysearchable/2.6.0+1.20.1.json
    translation: /roughlysearchable/2.6.0+1.20.1/%locale_with_underscore%.json
  - source: /shulkerboxtooltip/4.0.4+1.20.1.json
    translation: /shulkerboxtooltip/4.0.4+1.20.1/%locale_with_underscore%.json
    excluded_target_languages:
      - en-GB
      - fr
      - ko
      - pt-BR
      - ru
      - tr
      - uk
      - zh-CN
  - source: /sodium/0.5.3.json
    translation: /sodium/0.5.3/%locale_with_underscore%.json
  - source: /sodium-extra/0.5.1+mc1.20.1-build.112.json
    translation: /sodium-extra/0.5.1+mc1.20.1-build.112/%locale_with_underscore%.json
    excluded_target_languages:
      - cs
      - de-AT
      - de-CH
      - de
      - el
      - es-AR
      - es-MX
      - et
      - fi
      - fr-CA
      - fr
      - it
      - ja
      - ko
      - ms
      - pl
      - pt-BR
      - pt-PT
      - ru
      - th
      - tr
      - uk
      - vi
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /sound_physics_remastered/1.20.1-1.2.1.json
    translation: /sound_physics_remastered/1.20.1-1.2.1/%locale_with_underscore%.json
    excluded_target_languages:
      - pt-BR
      - ru
  - source: /spruceui/5.0.0+1.20.json
    translation: /spruceui/5.0.0+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - es-ES
      - es-MX
      - et
      - fr-CA
      - fr
      - it
      - pl
      - ru
      - zh-CN
      - zh-TW
  - source: /stack-to-nearby-chests/0.5.0.json
    translation: /stack-to-nearby-chests/0.5.0/%locale_with_underscore%.json
    excluded_target_languages:
      - zh-CN
  - source: /tweed4_tailor_screen/1.1.4+mc1.20-pre1.json
    translation: /tweed4_tailor_screen/1.1.4+mc1.20-pre1/%locale_with_underscore%.json
  - source: /visuality/0.7.1+1.20.json
    translation: /visuality/0.7.1+1.20/%locale_with_underscore%.json
    excluded_target_languages:
      - es-MX
      - pt-BR
      - ru
      - uk
      - zh-CN
  - source: /wakes/0.2.0.json
    translation: /wakes/0.2.0/%locale_with_underscore%.json
  - source: /waterdripsound/1.19-0.3.2.json
    translation: /waterdripsound/1.19-0.3.2/%locale_with_underscore%.json
  - source: /waveycapes/1.3.2.json
    translation: /waveycapes/1.3.2/%locale_with_underscore%.json
    excluded_target_languages:
      - fr
      - pt-BR
      - pt-PT
      - zh-CN
  - source: /xaerominimap/23.8.4.json
    translation: /xaerominimap/23.8.4/%locale_with_underscore%.json
    excluded_target_languages:
      - cs
      - da
      - de
      - el
      - es-AR
      - es-ES
      - es-MX
      - et
      - fr
      - hr
      - hu
      - id
      - it
      - ja
      - lv
      - nl
      - pl
      - pt-BR
      - pt-PT
      - ru
      - sr
      - th
      - tr
      - uk
      - zh-CN
  - source: /xaeroworldmap/1.36.0.json
    translation: /xaeroworldmap/1.36.0/%locale_with_underscore%.json
    excluded_target_languages:
      - de
  - source: /zoomify/2.11.2.json
    translation: /zoomify/2.11.2/%locale_with_underscore%.json
    excluded_target_languages:
      - de
      - en-GB
      - es-ES
      - es-MX
      - et
      - fr
      - ja
      - pt-BR
      - ru
      - tr
      - vi
      - zh-CN
      - zh-TW
