files:
  - source: /group_p59hrfe/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
  - source: /group_uq37rd2/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
  - source: /group_fy96ca4/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - zh-CN
  - source: /group_w1ed779/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - fr
  - source: /group_qdygrud/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - pt-BR
      - ru
  - source: /group_xbe3j1c/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - ru
      - zh-CN
  - source: /group_k9coegq/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - vi
      - zh-TW
  - source: /group_fobxhti/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - ru
      - zh-TW
  - source: /group_i43b1vh/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - zh-CN
      - zh-TW
  - source: /group_ni24c6r/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - fr
      - ru
  - source: /group_5jnfeau/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - ja
      - pt-BR
      - zh-CN
  - source: /group_iyv1csk/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - pt-BR
      - ru
      - zh-CN
  - source: /group_w1l2rq1/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - ru
      - zh-CN
  - source: /group_0bkaxyp/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - fr
      - pt-BR
      - zh-CN
  - source: /group_z08bfp4/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - ru
      - tr
      - zh-CN
  - source: /group_oki2n7x/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - fr
      - pt-BR
      - pt-PT
      - zh-CN
  - source: /group_3vtt0e8/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - pt-BR
      - ru
      - uk
      - zh-CN
  - source: /group_41qqnyu/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - es-ES
      - pt-BR
      - zh-TW
  - source: /group_kumzmn3/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - pt-BR
      - pt-PT
      - uk
      - zh-TW
  - source: /group_1due3a5/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - be
      - pt-BR
      - ru
      - zh-CN
      - zh-TW
  - source: /group_6f6a5ws/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - fi
      - fr
      - pt-BR
      - tt-RU
      - zh-CN
  - source: /group_p2kkf3l/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - es-MX
      - pt-BR
      - ru
      - uk
      - zh-CN
  - source: /group_nzs7a7t/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - fr
      - pt-BR
      - tt-RU
      - uk
      - zh-TW
  - source: /group_m769yjd/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - be
      - de
      - fr
      - ja
      - uk
      - zh-CN
  - source: /group_7k95l7k/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - et
      - fi
      - ru
      - zh-CN
      - zh-TW
  - source: /group_z6um4qb/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - ja
      - pt-BR
      - ru
      - tt-RU
      - uk
      - zh-CN
      - zh-TW
  - source: /group_630bb77/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - fr
      - it
      - pt-BR
      - ru
      - uk
      - vi
      - zh-TW
  - source: /group_lb9ucjl/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - ko
      - pt-BR
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /group_i5ema1b/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - el
      - fr
      - pt-BR
      - ru
      - vi
      - zh-CN
      - zh-TW
  - source: /group_4s7ol3e/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - et
      - it
      - ko
      - pt-BR
      - pt-PT
      - ru
      - tr
  - source: /group_fehngpk/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - es-AR
      - et
      - fi
      - fr
      - pl
      - pt-BR
      - zh-CN
  - source: /group_45arwf3/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - el
      - fr
      - pt-BR
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /group_zw1hx3x/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - en-GB
      - fr
      - ko
      - pt-BR
      - ru
      - tr
      - uk
      - zh-CN
  - source: /group_zg9k8ox/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - cs
      - ja
      - ko
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /group_3127oq7/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - fr
      - it
      - ko
      - pl
      - ru
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /group_h53rfml/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - en-GB
      - fr
      - ko
      - pt-BR
      - ru
      - sv-SE
      - uk
      - zh-CN
  - source: /group_9zhsosh/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - et
      - it
      - ko
      - pt-BR
      - ru
      - uk
      - zh-CN
      - zh-TW
  - source: /group_ceow4ge/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - et
      - fr-CA
      - it
      - pt-BR
      - ru
      - tr
      - vi
      - zh-CN
      - zh-TW
  - source: /group_zkhc78s/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - cs
      - de
      - fr
      - hy-AM
      - ko
      - pl
      - ru
      - uk
      - zh-CN
  - source: /group_g8p4z1w/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - el
      - et
      - ko
      - pl
      - pt-BR
      - ru
      - zh-CN
      - zh-TW
  - source: /group_2qmktrs/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - it
      - ja
      - ko
      - pl
      - pt-BR
      - ru
      - uk
      - zh-CN
      - zh-TW
  - source: /group_ae2j3fe/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - et
      - it
      - pl
      - ru
      - tr
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /group_j3ls858/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - be
      - el
      - et
      - fr
      - pl
      - pt-BR
      - ru
      - sl
      - tt-RU
      - zh-CN
      - zh-TW
  - source: /group_w97ypro/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - es-ES
      - es-MX
      - et
      - fr
      - fr-CA
      - it
      - pl
      - ru
      - zh-CN
      - zh-TW
  - source: /group_0u8y0rt/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - be
      - fr
      - it
      - ko
      - pl
      - pt-BR
      - ru
      - tt-RU
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /group_5mucwkh/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - bg
      - de
      - en-UD
      - et
      - fr
      - ja
      - lol
      - pt-BR
      - ru
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /group_83you42/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - en-GB
      - es-ES
      - es-MX
      - et
      - fr
      - ja
      - pt-BR
      - ru
      - tr
      - vi
      - zh-CN
      - zh-TW
  - source: /group_s6rge0a/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - cs
      - de
      - el
      - et
      - fil
      - fr
      - it
      - ko
      - pl
      - pt-BR
      - ru
      - uk
      - zh-CN
  - source: /group_2ftyfjj/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - cs
      - de
      - el
      - et
      - fr
      - id
      - it
      - pt-BR
      - pt-PT
      - ru
      - tr
      - tt-RU
      - zh-CN
      - zh-TW
  - source: /group_jz71tw8/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - es-MX
      - et
      - fr
      - fr-CA
      - hi
      - it
      - nl
      - pl
      - pt-BR
      - ru
      - sv-SE
      - tr
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /group_5jvgzfz/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - ca
      - cs
      - da
      - de
      - en-PT
      - es-ES
      - et
      - fi
      - fr
      - id
      - it
      - ja
      - ko
      - nl
      - pl
      - pt-BR
      - ro
      - ru
      - sk
      - th
      - tr
      - uk
      - vi
      - zh-CN
      - zh-TW
  - source: /group_9v0qgkc/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - cs
      - da
      - de
      - el
      - es-AR
      - es-ES
      - es-MX
      - et
      - fr
      - hr
      - hu
      - id
      - it
      - ja
      - lv
      - nl
      - pl
      - pt-BR
      - pt-PT
      - ru
      - sr
      - th
      - tr
      - uk
      - zh-CN
  - source: /group_bi9gofu/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - cs
      - de
      - de-CH
      - en-PT
      - en-UD
      - es-AR
      - es-ES
      - et
      - fa
      - fi
      - fr
      - hu
      - it
      - ja
      - ko
      - lol
      - nl
      - pl
      - pt-BR
      - ru
      - sk
      - th
      - tr
      - uk
      - zh-CN
      - zh-TW
  - source: /group_m56vm8o/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - cs
      - de
      - de-AT
      - de-CH
      - el
      - es-AR
      - es-MX
      - et
      - fi
      - fr
      - fr-CA
      - it
      - ja
      - ko
      - ms
      - pl
      - pt-BR
      - pt-PT
      - ru
      - th
      - tr
      - uk
      - vi
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /group_ffk9axb/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - bg
      - cs
      - da
      - de
      - en-GB
      - en-UD
      - eo
      - es-ES
      - et
      - fr
      - he
      - it
      - ja
      - ko
      - lol
      - nn-NO
      - pl
      - pt-BR
      - pt-PT
      - ru
      - tr
      - uk
      - vi
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /group_21j33r0/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - de
      - de-AT
      - de-CH
      - en-PT
      - es-AR
      - es-CL
      - es-EC
      - es-ES
      - es-MX
      - es-UY
      - es-VE
      - et
      - fr
      - fr-CA
      - it
      - ko
      - pl
      - pt-BR
      - pt-PT
      - ru
      - sv-SE
      - tr
      - uk
      - vi
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /group_zjox4t8/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - af
      - ar
      - ast
      - az
      - ba
      - be
      - ca
      - cs
      - cy
      - da
      - de
      - de-AT
      - de-CH
      - el
      - en-AU
      - en-CA
      - en-GB
      - en-NZ
      - en-PT
      - en-UD
      - eo
      - es-AR
      - es-CL
      - es-EC
      - es-ES
      - es-MX
      - es-UY
      - es-VE
      - et
      - eu
      - fa
      - fi
      - fil
      - fo
      - fr
      - fr-CA
      - fra-DE
      - fy-NL
      - ga-IE
      - gd
      - gl
      - haw
      - he
      - hi
      - hu
      - hy-AM
      - id
      - ido
      - ig
      - is
      - it
      - ja
      - jbo
      - ka
      - kk
      - kn
      - ko
      - la-LA
      - lb
      - li
      - lol
      - lt
      - lv
      - mk
      - mn
      - ms
      - mt
      - nds
      - nl
      - nl-BE
      - nn-NO
      - 'no'
      - oc
      - pl
      - pt-BR
      - pt-PT
      - qya-AA
      - ro
      - ru
      - se
      - sk
      - sl
      - so
      - sq
      - sr
      - sv-SE
      - ta
      - th
      - tl
      - tlh-AA
      - tr
      - tt-RU
      - uk
      - val-ES
      - vec
      - vi
      - yi
      - yo
      - zh-CN
      - zh-HK
      - zh-TW
  - source: /group_1s5y3xs/*/*.json
    translation: '/%original_path%/%file_name%/%locale%.json'
    excluded_target_languages:
      - af
      - ar
      - ast
      - az
      - ba
      - be
      - bg
      - br-FR
      - bs
      - ca
      - cs
      - cy
      - da
      - de
      - de-AT
      - de-CH
      - el
      - en-AU
      - en-CA
      - en-GB
      - en-NZ
      - en-PT
      - en-UD
      - eo
      - es-AR
      - es-CL
      - es-EC
      - es-ES
      - es-MX
      - es-UY
      - es-VE
      - et
      - eu
      - fa
      - fi
      - fil
      - fo
      - fr
      - fr-CA
      - fra-DE
      - fy-NL
      - ga-IE
      - gd
      - gl
      - haw
      - he
      - hi
      - hr
      - hu
      - hy-AM
      - id
      - ido
      - ig
      - is
      - it
      - ja
      - jbo
      - ka
      - kk
      - kn
      - ko
      - kw
      - la-LA
      - lb
      - li
      - lol
      - lt
      - lv
      - mi
      - mk
      - mn
      - ms
      - mt
      - nds
      - nl
      - nl-BE
      - nn-NO
      - 'no'
      - oc
      - pl
      - pt-BR
      - pt-PT
      - qya-AA
      - ro
      - ru
      - se
      - sk
      - sl
      - so
      - sq
      - sr
      - sv-SE
      - ta
      - th
      - tl
      - tlh-AA
      - tr
      - tt-RU
      - uk
      - val-ES
      - vec
      - vi
      - yi
      - yo
      - zh-CN
      - zh-HK
      - zh-TW
